version: '3.9'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
